title: Daniel DeGouveia
logo: "/images/circle-cropped.png?raw=true"
description: > 
  I am a Bachelorâ€™s of Science candidate in the field of Computer Science with a concentration in Software Engineering.
  <br><br>

  <a href="https://www.linkedin.com/in/danieldegouveia">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
